name: Release Workflow

on:
  workflow_dispatch:
  release:
    types: [published]
  # TODO remove after debugging
  push:
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  gh-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Prepare repository
        run: git fetch --unshallow --tags
      - name: Use Node.js
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: yarn install
      - name: Build Storybook
        run: yarn sb-build
      - name: Add CNAME for gh-pages
        run: |
          echo 'https://ui.kaizokulabs.com' > storybook-static/CNAME
      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          yarn deploy
